=== codeformuenster/familien-dashboard/import-scripts/sportstaetten-belegungsplan/source/bel.dtd
<!ELEMENT Von (#PCDATA)>
<!ELEMENT Bis (#PCDATA)>
<!ELEMENT Nummer (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT SegmentNr1 (#PCDATA)>
<!ELEMENT SegmentNr2 (#PCDATA)>
<!ELEMENT SegmentNr3 (#PCDATA)>
<!ELEMENT SegmentName (#PCDATA)>
<!ATTLIST Belegung ID CDATA #REQUIRED>
<!ELEMENT Datum (#PCDATA)>
<!ELEMENT Wochentag (#PCDATA)>
<!ELEMENT Start (#PCDATA)>
<!ELEMENT Ende (#PCDATA)>
<!ELEMENT Dauer (#PCDATA)>
<!ELEMENT Anfangsdatum (#PCDATA)>
<!ELEMENT Endedatum (#PCDATA)>
<!ELEMENT Saison (#PCDATA)>
<!ELEMENT Nutzer-NutzergruppenNr (#PCDATA)>
<!ELEMENT Nutzer-Nutzergruppe (#PCDATA)>
<!ELEMENT Nutzer-NutzergruppeKng (#PCDATA)>
<!ELEMENT Taetigkeit (#PCDATA)>
<!ELEMENT Bereich (#PCDATA)>
<!ELEMENT BelegungstypKey (#PCDATA)>
<!ELEMENT Belegungstyp (#PCDATA)>
<!ELEMENT Kommentar1 (#PCDATA)>
<!ELEMENT Kommentar2 (#PCDATA)>
<!ELEMENT Kng (#PCDATA)>
<!ELEMENT DatumGeaendert (#PCDATA)>
<!ELEMENT DatumErstellt (#PCDATA)>
<!ELEMENT TeilnehmerzahlGesamt (#PCDATA)>
<!ELEMENT TeilnehmerzahlMax (#PCDATA)>
<!ELEMENT SegNr1 (#PCDATA)>
<!ELEMENT SegNr2 (#PCDATA)>
<!ELEMENT SegNr3 (#PCDATA)>
<!ELEMENT SegName (#PCDATA)>
<!ELEMENT Belegungen (Zeitraum,Einrichtung*)>
<!ELEMENT Zeitraum (Von?,Bis?)>
<!ELEMENT Einrichtung (Nummer?,Name?,Segmente+,Einrichtungsbelegungen*)>
<!ELEMENT Segmente (Segment*)>
<!ELEMENT Segment (SegmentNr1?,SegmentNr2?,SegmentNr3?,SegmentName?)>
<!ELEMENT Einrichtungsbelegungen (Belegung*)>
<!ELEMENT Belegung (Datum?,Start?,Ende?,Dauer?,Nutzer-NutzergruppenNr?,Nutzer-Nutzergruppe?,Nutzer-NutzergruppeKng?,Taetigkeit?,Bereich?,Belegungstyp?,Kommentar1?,Kommentar2?,Kng?,DatumGeaendert?,DatumErstellt?,TeilnehmerzahlGesamt?,TeilnehmerzahlMax?,SegNr1?,SegNr2?,SegNr3?,SegName?)>

=== codeformuenster/familien-dashboard/data/sportstaetten_belegungsplan/source/bel_test.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE Belegungen SYSTEM "bel.dtd">
<Belegungen>
  <Zeitraum>
      <Von>13.10.2017</Von>
      <Bis>20.01.2018</Bis>
  </Zeitraum>
    <Einrichtung>
        <Nummer>00001</Nummer>
        <Name>Aaseesporthalle</Name>
    <Segmente>
    <Segment>
        <SegmentNr1>G</SegmentNr1>
        <SegmentName>Gesamtspielfläche</SegmentName>
      </Segment>
    <Segment>
        <SegmentNr1>G</SegmentNr1>
        <SegmentNr2>S1</SegmentNr2>
        <SegmentName>Segment 1</SegmentName>
      </Segment>
    <Segment>
        <SegmentNr1>G</SegmentNr1>
        <SegmentNr2>S2</SegmentNr2>
        <SegmentName>Segment 2</SegmentName>
      </Segment>
    <Segment>
        <SegmentNr1>G</SegmentNr1>
        <SegmentNr2>S3</SegmentNr2>
        <SegmentName>Segment 3</SegmentName>
      </Segment>
      </Segmente>
    <Einrichtungsbelegungen>
      <Belegung ID="1">
          <Datum>13.10.2017</Datum>
          <Wochentag>Fr</Wochentag>
          <Start>08:00</Start>
          <Ende>09:30</Ende>
          <Dauer>01:30</Dauer>
          <Anfangsdatum>07.09.2011</Anfangsdatum>
          <Endedatum>00.00.0000</Endedatum>
          <Saison></Saison>
          <Nutzer-NutzergruppenNr></Nutzer-NutzergruppenNr>
          <Nutzer-Nutzergruppe></Nutzer-Nutzergruppe>
          <Nutzer-NutzergruppeKng>V</Nutzer-NutzergruppeKng>
          <Taetigkeit></Taetigkeit>
          <Bereich>Schulsport</Bereich>
          <BelegungstypKey></BelegungstypKey>
          <Belegungstyp></Belegungstyp>
          <Kommentar1></Kommentar1>
          <Kommentar2></Kommentar2>
          <Kng>P</Kng>
          <DatumGeaendert>00.00.0000</DatumGeaendert>
          <DatumErstellt>00.00.0000</DatumErstellt>
          <TeilnehmerzahlGesamt>0</TeilnehmerzahlGesamt>
          <TeilnehmerzahlMax>0</TeilnehmerzahlMax>
          <SegNr1>G</SegNr1>
          <SegNr2>S1</SegNr2>
          <SegNr3></SegNr3>
          <SegName>Segment 1</SegName>
        </Belegung>
        <Belegung ID="2">
            <Datum>13.10.2017</Datum>
            <Wochentag>Fr</Wochentag>
            <Start>08:00</Start>
            <Ende>10:30</Ende>
            <Dauer>02:30</Dauer>
            <Anfangsdatum>26.08.2015</Anfangsdatum>
            <Endedatum>00.00.0000</Endedatum>
            <Saison></Saison>
            <Nutzer-NutzergruppenNr></Nutzer-NutzergruppenNr>
            <Nutzer-Nutzergruppe></Nutzer-Nutzergruppe>
            <Nutzer-NutzergruppeKng>V</Nutzer-NutzergruppeKng>
            <Taetigkeit></Taetigkeit>
            <Bereich>Schulsport</Bereich>
            <BelegungstypKey></BelegungstypKey>
            <Belegungstyp></Belegungstyp>
            <Kommentar1></Kommentar1>
            <Kommentar2></Kommentar2>
            <Kng>P</Kng>
            <DatumGeaendert>00.00.0000</DatumGeaendert>
            <DatumErstellt>00.00.0000</DatumErstellt>
            <TeilnehmerzahlGesamt>0</TeilnehmerzahlGesamt>
            <TeilnehmerzahlMax>0</TeilnehmerzahlMax>
            <SegNr1>G</SegNr1>
            <SegNr2>S3</SegNr2>
            <SegNr3></SegNr3>
            <SegName>Segment 3</SegName>
          </Belegung>
<Belegung ID="5">
    <Datum>13.10.2017</Datum>
    <Wochentag>Fr</Wochentag>
    <Start>10:30</Start>
    <Ende>11:45</Ende>
    <Dauer>01:15</Dauer>
    <Anfangsdatum>27.06.2001</Anfangsdatum>
    <Endedatum>00.00.0000</Endedatum>
    <Saison></Saison>
    <Nutzer-NutzergruppenNr></Nutzer-NutzergruppenNr>
    <Nutzer-Nutzergruppe></Nutzer-Nutzergruppe>
    <Nutzer-NutzergruppeKng>V</Nutzer-NutzergruppeKng>
    <Taetigkeit>Kinderturnen</Taetigkeit>
    <Bereich>Breitensport</Bereich>
    <BelegungstypKey></BelegungstypKey>
    <Belegungstyp></Belegungstyp>
    <Kommentar1></Kommentar1>
    <Kommentar2></Kommentar2>
    <Kng>P</Kng>
    <DatumGeaendert>07.07.2009</DatumGeaendert>
    <DatumErstellt>00.00.0000</DatumErstellt>
    <TeilnehmerzahlGesamt>0</TeilnehmerzahlGesamt>
    <TeilnehmerzahlMax>0</TeilnehmerzahlMax>
    <SegNr1>G</SegNr1>
    <SegNr2>S3</SegNr2>
    <SegNr3></SegNr3>
    <SegName>Segment 3</SegName>
  </Belegung>
<Belegung ID="7">
    <Datum>13.10.2017</Datum>
    <Wochentag>Fr</Wochentag>
    <Start>14:30</Start>
    <Ende>16:00</Ende>
    <Dauer>01:30</Dauer>
    <Anfangsdatum>00.00.0000</Anfangsdatum>
    <Endedatum>00.00.0000</Endedatum>
    <Saison></Saison>
    <Nutzer-NutzergruppenNr>003130</Nutzer-NutzergruppenNr>
    <Nutzer-Nutzergruppe>Sportverein Blau-Weiß Aasee e.V.</Nutzer-Nutzergruppe>
    <Nutzer-NutzergruppeKng>V</Nutzer-NutzergruppeKng>
    <Taetigkeit>Turnen</Taetigkeit>
    <Bereich>Breitensport</Bereich>
    <BelegungstypKey></BelegungstypKey>
    <Belegungstyp></Belegungstyp>
    <Kommentar1>sportmotorische Grundausbildung</Kommentar1>
    <Kommentar2></Kommentar2>
    <Kng>P</Kng>
    <DatumGeaendert>00.00.0000</DatumGeaendert>
    <DatumErstellt>00.00.0000</DatumErstellt>
    <TeilnehmerzahlGesamt>0</TeilnehmerzahlGesamt>
    <TeilnehmerzahlMax>0</TeilnehmerzahlMax>
    <SegNr1>G</SegNr1>
    <SegNr2>S1</SegNr2>
    <SegNr3></SegNr3>
    <SegName>Segment 1</SegName>
  </Belegung>
      </Einrichtungsbelegungen>
  </Einrichtung>
</Belegungen>
